# Based on the example seen on 
# http://blog.scottlowe.org/2015/02/10/using-docker-with-vagrant/

# So that we don't have to remember to add '--provider docker' in cli
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  config.vm.define "docker"

  config.vm.provider "docker" do |docker|
      # Using a VM instead of boot2docker
      docker.vagrant_vagrantfile = "centos7/Vagrantfile"
      docker.vagrant_machine = "docker-host"
      # The image name is from Docker Hub (vs. Vagrant Atlas)
      docker.image = "nginx"
      docker.ports = ['80:80', '443:443']
      docker.name = 'nginx-container'

      # If set false (by default), vagrang complains about not being able
      # ssh into the docker
      docker.has_ssh = true
  end
  
  # Disabling folder sync for now
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
